### ISSUE TITLE
Minor clean up issue

### ISSUE THREAD

**Issue by 7890** [kmatheussen/jack_capture#19]
Hi,
adding 

```
vringbuffer_delete(vringbuffer);
```

to jack_capture.c would be a welcome amendment, that serves in special cases (or just for completeness).
https://github.com/kmatheussen/jack_capture/blob/master/jack_capture.c#L2651

http://stackoverflow.com/questions/2213627/when-you-exit-a-c-application-is-the-malloc-ed-memory-automatically-freed says that it's not certain memory will be release after quit.

I've inserted a shared memory backed ringbuffer that replaces jack_ringbuffer for fun and to see if jack_capture will work as familiar, then found all ringbuffers to be remaining in /dev/shm/ after quit. The above solved the issue although it might not be necessary for other cases.

Btw, +1 for jack_capture, which is IMO the best command line recording program!
Best regards

**Comment by kmatheussen** [comment]
I think all operating systems that jack_capture runs on releases memory when a process exits. Most programs depends on that behavior, and in jack_capture vringbuffer is not the only memory that is not freed when exiting the program.

**Comment by 7890** [comment]
Yes it's pretty common, it doesn't seem to matter in that case.
