### ISSUE TITLE
Issue with recording longer sessions when compiled for 32 bits

### ISSUE THREAD

**Issue by jkroll20** [kmatheussen/jack_capture#21]
Hi,

someone on LAU reported that jack_record stops recording after a file size of 2.1 GB is reached when compiled for 32 bits. The problem does not appear when built for a 64-bit OS.

Problem description: http://lists.linuxaudio.org/pipermail/linux-audio-user/2016-November/106647.html
See also this post: http://lists.linuxaudio.org/pipermail/linux-audio-user/2016-November/106670.html

Best,
J.

**Comment by kmatheussen** [comment]
This problem is not related to jack_capture.

**Comment by jkroll20** [comment]
Then what is it related to?

**Comment by kmatheussen** [comment]
*Don't know. Quick google:*
*Perhaps libsndfile isn't compiled with **_LARGEFILE64_SOURCE?*

*https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html#Feature-Test-Macros
<https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html#Feature-Test-Macros>*
