### ISSUE TITLE
Program exits after recording stopped in timemachine mode.

### ISSUE THREAD

**Issue by nothingimaginative** [kmatheussen/jack_capture#23]
Hello,
I am using jack_capture version 0.9.71 (installed via apt-get in Ubuntu 16.04), with JACK in non-realtime mode.

Starting the program with `jack_capture -tm` in a terminal starts the program in timemachine mode as expected. After pressing return, the program gives the "writing data all to disk" and "Finished" messages, prints the line `>>> Error: exec returned.` and exits.

Is this the intended outcome? It would be preferable for me if the program continued and maintained the timemachine buffer from where the recording stops.

Example outputs:

- In timemachine mode:

> ```
> ~$ jack_capture -tm
> Cannot lock down 82274202 byte memory area (Cannot allocate memory)
> >>> Warning. Could not set higher priority for a SCHED_FIFO process using setpriority().
> >>> Waiting to start recording of "jack_capture_05.wav"
> >>> Press <Ctrl-C> to stop recording and quit.
> >>> Recording. Press <Return> to stop.                                
> >>> Please wait while writing all data to disk. (shouldn't take long) 
>    |"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""|
> 00:|                                                                 |
> 01:|                                                                 |
> Buffer: 12.03s./12.03s  Time: 0.11m.   DHP: [ ]  Overruns: 0  Xruns: 0
> Finished.
> >>> Error: exec returned.
> ```

- In normal mode:

> ```
> ~$ jack_capture
> Cannot lock down 82274202 byte memory area (Cannot allocate memory)
> >>> Warning. Could not set higher priority for a SCHED_FIFO process using setpriority().
> >>> Recording to "jack_capture_06.wav". Press <Return> or <Ctrl-C> to stop.
> >>> Please wait while writing all data to disk. (shouldn't take long) 
>    |"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""|
> 00:|                                                                 |
> 01:|                                                                 |
> Buffer: 4.04s./4.04s    Time: 0.08m.   DHP: [ ]  Overruns: 0  Xruns: 0
> Finished.
> ```

Thank you for the time and effort spent into this program!
Regards,
Ian

**Comment by kmatheussen** [comment]
I think this is a bug that was been fixed in 0.9.72.

**Comment by kmatheussen** [comment]
It might work to give the full path to jack_capture:

/usr/bin/jack_capture -tm

**Comment by nothingimaginative** [comment]
Providing the full path worked in 0.9.71. Thank you for your help!
