### ISSUE TITLE
jack_capture_gui2 SIGABRT - free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by fordfrog** [kmatheussen/jack_capture#30]
i just packaged jack_capture on gentoo linux and when testing it, i found out that jack_capture_gui2 does not start and instead crashes:

```
$ LC_ALL=C jack_capture_gui2 
free(): double free detected in tcache 2
Neúspěšně ukončen (SIGABRT)

```
is jack_capture_gui2 still supported or it should not be used anymore?

**Comment by kmatheussen** [comment]
It should definitely not be used anymore. It was removed from the target list in 2011.

**Comment by fordfrog** [comment]
thank you, will remove it from the package :-)
