### ISSUE TITLE
jack-transport-multi in not working

### ISSUE THREAD

**Issue by diegodorado** [kmatheussen/jack_capture#34]
the `jack-transport-multi` option is documented but not being parsed on `jack_capture.c`
Is that right?

**Comment by kmatheussen** [comment]
Yes. In the documentation, and for "--help", it also says "(not implemented yet)".

**Comment by kmatheussen** [comment]
This this workaround should work:
```
while true ; do jack_capture -jt ; done
```

**Comment by diegodorado** [comment]
nice workaround, thanks!
