### ISSUE TITLE
master build issue here ...

### ISSUE THREAD

**Issue by CaptainBloodz** [kmatheussen/jack_capture#39]
`1 out of 3 hunks FAILED -- saving rejects to file Makefile.rej                                                                                                                                              [ !! ]
 * ERROR: media-sound/jack_capture-9999::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-sound/jack_capture-9999/files/jack_capture-0.9.73-Makefile.patch
 * `

[jack_capture-0.9.73-Makefile.patch.zip](https://github.com/kmatheussen/jack_capture/files/4674407/jack_capture-0.9.73-Makefile.patch.zip)

More likely to be intended to  gentoo packagers.

Thks 4 ur attention, interest & support.

**Comment by kmatheussen** [comment]
Yes, I think this is a gentoo issue.
