### ISSUE TITLE
at 192Khz sample rate clock runs at half speed recording speed doubled

### ISSUE THREAD

**Issue by Claudenw** [kmatheussen/jack_capture#43]
When I record a jack stream at 192kHz rate the recording speed is doubled.  That is when I play it back it plays at double speed.  In addition, I have a clock display on the system and it shows that the recording time calculated by the -V switch is 1/2 the rate it should be.  (e.g. 10 seconds wall clock is 5 seconds jack_capture -V clock)

If I use the jack_connect and connect the ports to other services the signal is correctly interpreted.

# Environment:

 * OS: Raspian  
 * Uname -a: Linux cuimhne-bd4bc2f8 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux
 * Platform: Pi 3 A+
 * Soundcard: pisound
 * Jack start command:  /usr/bin/jackd -t 2000 -R -P 95 -d alsa -d hw:pisound -r 192000 -p 1024 -n 2 -X seq -s
 * Jack_capture command:  jack_capture -V <filename>

**Comment by kmatheussen** [comment]
That sounds strange. Can you post the output of these two commands?
```
jack_capture -d 5 /tmp/5sec.wav
sndfile-info /tmp/5sec.wav
```

Here's my output:
```

Version : libsndfile-1.0.25

========================================
File : /tmp/5sec.wav
Length : 7680088
RIFF : 7680080
WAVE
fmt  : 16
  Format        : 0x3 => WAVE_FORMAT_IEEE_FLOAT
  Channels      : 2
  Sample Rate   : 192000
  Block Align   : 8
  Bit Width     : 32
  Bytes/sec     : 1536000
fact : 4
  frames  : 960000
PEAK : 24
  version    : 1
  time stamp : 1610273039
    Ch   Position       Value
     0   0              0
     1   0              0
data : 7680000
End

----------------------------------------
Sample Rate : 192000
Frames      : 960000
Channels    : 2
Format      : 0x00010006
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:05.000
Signal Max  : 0 (-inf dB)
```

**Comment by kmatheussen** [comment]
Also, which version of jack_capture are you using?
```
jack_capture --version
```

**Comment by Claudenw** [comment]
```
sndfile-info /recordings/5sec.wav
========================================
File : /recordings/5sec.wav
Length : 7680088
RIFF : 7680080
WAVE
fmt  : 16
  Format        : 0x3 => WAVE_FORMAT_IEEE_FLOAT
  Channels      : 2
  Sample Rate   : 192000
  Block Align   : 8
  Bit Width     : 32
  Bytes/sec     : 1536000
fact : 4
  frames  : 960000
PEAK : 24
  version    : 1
  time stamp : 1610274863
    Ch   Position       Value
     0   0              0
     1   0              0
data : 7680000
End

----------------------------------------
Sample Rate : 192000
Frames      : 960000
Channels    : 2
Format      : 0x00010006
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:05.000
Signal Max  : 0 (-inf dB)
```

```
jack_capture --version
0.9.73
```

I installed the latest version of jack_capture before running the test.  Same issue with time  wall clock shows 10 seconds.

**Comment by kmatheussen** [comment]
Can you post the output of this command too please:
```
time ./jack_capture --disable-console -d 5 /tmp/5sec.wav
```
Thanks.

My output:
```>>> Warning. Could not set higher priority for a SCHED_OTHER process using setpriority().
>>> 
>>> !!! Warning, Overwriting existing file /tmp/5sec.wav !!!
>>> 
>>> Recording to "/tmp/5sec.wav". The recording is going
>>> to last 5.000000 seconds Press <Ctrl-C> to stop before that.
>>> Please wait while writing all data to disk. (shouldn't take long)
Finished.

real    0m5.137s
user    0m0.061s
sys     0m0.114s

```

**Comment by kmatheussen** [comment]
Which version of  jackd are you using?
```
jackd --version
```

**Comment by Claudenw** [comment]
```
time jack_capture --disable-console -d 5 /recordings/5sec.wav
>>> Warning. Could not set higher priority for a SCHED_OTHER process using setpriority().
>>> 
>>> !!! Warning, Overwriting existing file /recordings/5sec.wav !!!
>>> 
>>> Recording to "/recordings/5sec.wav". The recording is going
>>> to last 5.000000 seconds Press <Ctrl-C> to stop before that.
>>> Please wait while writing all data to disk. (shouldn't take long)
Finished.

real	0m10.332s
user	0m0.269s
sys	0m0.185s
```

```
jackd --version
jackdmp version 1.9.12 tmpdir /dev/shm protocol 8
```

**Comment by kmatheussen** [comment]
Thank you. As far as I can see, this is not a bug in jack_capture. It seems like jack reports a samplerate of 192khz, while in reality the samplerate is 96khz. I don't know whether this is a bug in Jack or in the alsa driver. My guess is that it's a bug in the alsa driver but I've created a ticket on the jack2 page just in case: https://github.com/kmatheussen/jack_capture/issues/43

**Comment by kmatheussen** [comment]
Please continue the discussion there, or report a bug to alsa.

**Comment by Claudenw** [comment]
thank you.

**Comment by kmatheussen** [comment]
I posted wrong link to the ticket above. Here is the right link: https://github.com/jackaudio/jack2/issues/702

(In recent versions of firefox I have to double-click the URL three times (!) for it to be copied to the clipboard. This constantly leads me to pasting the wrong links (or non-links), Haven't figured out how to fix this.)

**Comment by Claudenw** [comment]
For completenss:

I believe the ALSA driver is supported by blokas (the developers of pisound) and so have opened a discussion on their site in hopes that if it is the ALSA driver they will have some insight:
https://community.blokas.io/t/at-192khz-sample-rate-clock-runs-at-half-speed-recording-speed-doubled/2598
