### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock vrb->increase_lock

### ISSUE THREAD

**Issue by ycaibb** [kmatheussen/jack_capture#47]
Hi, developers, thank you for your checking. It seems the lock `vrb->increase_lock` is not released correctly when `das_buffer==NULL` in the function `vringbuffer_increase_writer1`?

https://github.com/kmatheussen/jack_capture/blob/e2c0c3d25fce0a13f3f18c622079cd29178af7f8/vringbuffer.c#L129-L139

**Comment by kmatheussen** [comment]
Thanks. Fixed. It was in practice a no-op though, and could never have causes any real problems as far as I could see. The only problem in the code was that out of memory during program startup was not properly handled.

**Comment by ycaibb** [comment]
OK，thank you for your explanation！
